//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_QuanLiSieuThi.Models.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BillDetail
    {
        [Required]
        public int BillID { get; set; }
        [Required]
        public int ProductID { get; set; }
        public string Type { get; set; }
        [Required]
        public int Amount { get; set; }
        [Required]
        public int UnitPrice { get; set; }
        [Required]
        public System.DateTime Date { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Product Product { get; set; }
    }
}
